Repository DataBiosphere/terra-workspace-data-service, pull requests merged in 2023-07, with the labels that each got.

#291 AJ-1091: Disallow any whitespace in TSV headers
  service/src/main/java/org/databiosphere/workspacedataservice/service/TsvStreamWriteHandler.java
  service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java
Labels: bug

#290 AJ-1126: Adjust logic to get wds endpoint url in python doc
  docs/WDS Python Client.md
Labels: chore

#296 AJ-1075: expose chart version and docker image version in /version api
  service/src/main/resources/application.properties
  service/src/main/resources/static/swagger/openapi-docs.yaml
Labels: feature
