Repository DataBiosphere/terra-workspace-data-service, pull requests merged in 2023-05, with the labels that each got.

#238 AJ-769: activity logging
  service/src/main/java/org/databiosphere/workspacedataservice/activitylog/ActivityEvent.java
  service/src/main/java/org/databiosphere/workspacedataservice/activitylog/ActivityEventBuilder.java
  service/src/main/java/org/databiosphere/workspacedataservice/activitylog/ActivityLogger.java
  service/src/main/java/org/databiosphere/workspacedataservice/activitylog/ActivityLoggerConfig.java
  service/src/main/java/org/databiosphere/workspacedataservice/activitylog/ActivityModels.java
  service/src/main/java/org/databiosphere/workspacedataservice/controller/DataRepoController.java
  service/src/main/java/org/databiosphere/workspacedataservice/sam/HttpSamClientFactory.java
  service/src/main/java/org/databiosphere/workspacedataservice/sam/HttpSamClientSupport.java
  service/src/main/java/org/databiosphere/workspacedataservice/sam/HttpSamDao.java
  service/src/main/java/org/databiosphere/workspacedataservice/sam/MisconfiguredSamDao.java
  service/src/main/java/org/databiosphere/workspacedataservice/sam/SamClientFactory.java
  service/src/main/java/org/databiosphere/workspacedataservice/sam/SamDao.java
  service/src/main/java/org/databiosphere/workspacedataservice/service/DataRepoService.java
  service/src/main/java/org/databiosphere/workspacedataservice/service/InstanceService.java
  service/src/main/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorService.java
  service/src/main/resources/ehcache.xml
  service/src/test/java/org/databiosphere/workspacedataservice/activitylog/ActivityEventBuilderTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/activitylog/LogStatementTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/sam/MockSamClientFactory.java
  service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceNoPermissionSamTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceSamExceptionTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceSamTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/service/InstanceServiceTest.java
Labels: enhancement

#235 AJ-995 - Fix error in the status response
  service/src/main/resources/static/swagger/openapi-docs.yaml
  service/src/test/java/org/databiosphere/workspacedataservice/GeneratedClientTests.java
Labels: bug

#247 AJ-1028 Fix PostgreSQL error caused by blank TSV headers
  service/src/main/java/org/databiosphere/workspacedataservice/service/TsvStreamWriteHandler.java
  service/src/main/java/org/databiosphere/workspacedataservice/shared/model/RecordAttributes.java
  service/src/test/java/org/databiosphere/workspacedataservice/controller/RecordControllerMockMvcTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/shared/model/RecordAttributesTest.java
Labels: bug

#249 AJ-945 - Adjust PR template wording
  pull_request_template.md
Labels: skip-changelog

#239 AJ-1010 Add a placeholder table on TDR import
  service/src/main/java/org/databiosphere/workspacedataservice/controller/DataRepoController.java
  service/src/main/java/org/databiosphere/workspacedataservice/datarepo/DataRepoDao.java
  service/src/main/java/org/databiosphere/workspacedataservice/service/DataRepoService.java
  service/src/test/java/org/databiosphere/workspacedataservice/activitylog/LogStatementTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/controller/DataRepoControllerMockMvcTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/datarepo/DataRepoDaoTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/datarepo/DataRepoServiceTest.java
  service/src/test/resources/nginx.conf
Labels: feature

#255 AJ-1063: update release-drafter template
  .github/release-drafter-config.yml
Labels: skip-changelog
