Repository DataBiosphere/terra-workspace-data-service, pull requests merged in 2024-03, with the labels that each got.

#621 AJ-1649: add @DirtiesContext to more tests
  service/src/test/java/org/databiosphere/workspacedataservice/config/TwdsPropertiesDataPlaneTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/jobexec/QuartzJobTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSinkTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/service/JobServiceControlPlaneTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/service/RecordServiceTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/storage/GcsStorageTest.java
Labels: chore

#620 AJ-1673: pfb import must use collection's workspaceid
  service/src/main/java/org/databiosphere/workspacedataservice/dataimport/WsmSnapshotSupport.java
  service/src/main/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJob.java
  service/src/main/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJob.java
  service/src/main/java/org/databiosphere/workspacedataservice/workspacemanager/WorkspaceManagerConfig.java
  service/src/main/java/org/databiosphere/workspacedataservice/workspacemanager/WorkspaceManagerDao.java
  service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbTestSupport.java
  service/src/test/java/org/databiosphere/workspacedataservice/pact/WsmPactTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/workspacemanager/WorkspaceManagerDaoTest.java
Labels: bug

#622 AJ-1673: TDR snapshot imports use the correct workspaceId
  service/src/main/java/org/databiosphere/workspacedataservice/dataimport/WsmSnapshotSupport.java
  service/src/main/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJob.java
  service/src/main/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJob.java
  service/src/main/java/org/databiosphere/workspacedataservice/service/CollectionService.java
  service/src/test/java/org/databiosphere/workspacedataservice/dataimport/WdsSnapshotSupportTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJobTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrTestSupport.java
  service/src/test/java/org/databiosphere/workspacedataservice/pact/WsmPactTest.java
Labels: bug

#602 AJ-1633: Finish wiring up `deleteCollection`
  service/src/main/java/org/databiosphere/workspacedataservice/config/TenancyProperties.java
  service/src/main/java/org/databiosphere/workspacedataservice/sam/HttpSamAuthorizationDao.java
  service/src/main/java/org/databiosphere/workspacedataservice/sam/SamAuthorizationDao.java
  service/src/main/java/org/databiosphere/workspacedataservice/sam/SamAuthorizationDaoFactory.java
  service/src/main/java/org/databiosphere/workspacedataservice/service/CollectionService.java
  service/src/main/resources/application-control-plane.yml
  service/src/main/resources/application-data-plane.yml
  service/src/main/resources/application.yml
  service/src/test/java/org/databiosphere/workspacedataservice/config/TwdsPropertiesControlPlaneTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/config/TwdsPropertiesDataPlaneTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/dao/MockCollectionDao.java
  service/src/test/java/org/databiosphere/workspacedataservice/dao/MockCollectionDaoConfig.java
  service/src/test/java/org/databiosphere/workspacedataservice/pact/SamPactTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/sam/MockSamAuthorizationDao.java
  service/src/test/java/org/databiosphere/workspacedataservice/service/CollectionServiceGetWorkspaceIdTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/service/CollectionServiceNoPermissionSamTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/service/CollectionServiceSamExceptionTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/service/CollectionServiceSamTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/service/ImportServiceDataPlaneTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/service/JobServiceDataPlaneTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/startup/CollectionInitializerBeanTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/startup/CollectionInitializerNoWorkspaceIdTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/tsv/TsvErrorMessageTest.java
Labels: enhancement

#596 AJ-1586 cWDS sends pubsub to Rawls
  README.md
  service/build.gradle
  service/src/main/java/org/databiosphere/workspacedataservice/dataimport/ImportDetails.java
  service/src/main/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJob.java
  service/src/main/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJob.java
  service/src/main/java/org/databiosphere/workspacedataservice/pubsub/ImportPubSub.java
  service/src/main/java/org/databiosphere/workspacedataservice/pubsub/NoopPubSub.java
  service/src/main/java/org/databiosphere/workspacedataservice/pubsub/PubSub.java
  service/src/main/java/org/databiosphere/workspacedataservice/pubsub/PubSubConfig.java
  service/src/main/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSink.java
  service/src/main/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSinkFactory.java
  service/src/main/java/org/databiosphere/workspacedataservice/recordsink/RecordSinkFactory.java
  service/src/main/java/org/databiosphere/workspacedataservice/recordsink/WdsRecordSinkFactory.java
  service/src/main/java/org/databiosphere/workspacedataservice/sam/HttpSamDao.java
  service/src/main/java/org/databiosphere/workspacedataservice/sam/SamDao.java
  service/src/main/java/org/databiosphere/workspacedataservice/service/RecordOrchestratorService.java
  service/src/main/java/org/databiosphere/workspacedataservice/storage/GcsStorage.java
  service/src/main/resources/application-control-plane.yml
  service/src/main/resources/application-data-plane.yml
  service/src/main/resources/application-local.yml
  service/src/test/java/org/databiosphere/workspacedataservice/annotations/AnnotatedApisTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/common/TestBase.java
  service/src/test/java/org/databiosphere/workspacedataservice/config/TwdsPropertiesControlPlaneTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobControlPlaneE2ETest.java
  service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbQuartzJobTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/dataimport/pfb/PfbTestSupport.java
  service/src/test/java/org/databiosphere/workspacedataservice/dataimport/tdr/TdrManifestQuartzJobTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/recordsink/RawlsRecordSinkTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/service/BatchWriteServiceTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/service/ImportServiceControlPlaneTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/service/JobServiceControlPlaneTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/storage/GcsStorageTest.java
  service/src/test/java/org/databiosphere/workspacedataservice/workspacemanager/WorkspaceManagerDaoTest.java
  service/src/test/resources/nginx.conf
Labels: feature
